bidaf:
    dropout: 0.2
    num_highways: 2
    num_lstm: 2
    hidden_size: 128
    embedding_dim: 128
    embedding_reduce: 100
    max_len: 50
    characters:
        dim: 16
        num_filters: 100
        filter_sizes:
            - 5

training:
    lr: 0.01
    betas:
        - 0.9
        - 0.999
    eps: 0.00000001
    weigth_decay: 0
    epochs: 20
    batch_size: 2
    vocab_size: 50000
    limit: 400
    teacher_forcing_ratio: 1.0
